#!/bin/bash

JETTY_VERSION='9.1.3'
JETTY_HOME_REAL="/opt/jetty_$JETTY_VERSION"
JETTY_HOME="/opt/jetty"

ln -sf "$JETTY_HOME_REAL" "$JETTY_HOME" 

if ! getent passwd 'jetty' > /dev/null 2>&1; then
	useradd jetty || true
	chown -R jetty "$JETTY_HOME"
fi

ln -fs "$JETTY_HOME/conf/jetty" /etc/default/jetty
ln -fs "$JETTY_HOME/bin/jetty.sh" /etc/init.d/jetty
chmod -R 777 "/etc/init.d/jetty" || true
chmod -R 777 "$JETTY_HOME_REAL" || true
/etc/init.d/jetty start || echo "Can't start jetty" 
